name: Build

on:
  push:
    tags-ignore:
      - "**"
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: docker://morphy/revive-action:v2
        with:
          config: "./revive.toml"
          path: "./..."

  test:
    name: Test
    needs: lint
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Run tests
      run: |
        COVERPKG=$(go list ./... | tr '\n' ,)
        COVERPKG=${COVERPKG%?}
        go test -race -coverpkg=${COVERPKG} -coverprofile=coverage.out -covermode=atomic ./...
      shell: bash
    - name: Upload coverage report
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: coverage.out
        flag-name: Go-${{ matrix.go }}
        parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
