name: Build

on:
  push:
    tags-ignore:
      - "**"
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: docker://morphy/revive-action:v2
        with:
          config: "./revive.toml"
          path: "./..."

  test:
    needs: lint
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Run tests
      run: go test ./...
